#!/usr/bin/env python

import os.path
import sys
from optparse import OptionParser

parser = OptionParser()

parser.add_option("-p", "--param", dest = "param", action = "append",
                  help = "CHARMM parameter file name (can be specified multiple-time)",
                  default = [])

parser.add_option("-t", "--psf", dest = "topology",
                  help="PSF file name")

# can be specified; otherwise specify interactively
parser.add_option("-s", "--solute", dest = "solute",
                  help = "Segment name of solute molecule",
                  default = None)

parser.add_option("-v", "--verbose", dest = "verbose", action="store_true",
                  help = "Be more verbose",
                  default = False)

(options, args) = parser.parse_args()

def warn_or_error(x, col):
    prefix = ""
    suffix = ""
    if os.isatty(sys.stderr.fileno()):
        prefix = "\x1b[" + str(col) + ";1m"
        suffix = "\x1b[0m"
    print >> sys.stderr, prefix + x + suffix

def error(x):
    warn_or_error("Error: " + x, 31)
    sys.exit(1)

def check_exists(f):
    if not os.path.exists(f):
        error(""+f+" file does not exist")

if options.param == None:
    error("param file is not specified (try --help)")
if options.topology == None:
    error("psf file is not specified (try --help)")

check_exists(options.topology)
opt="  --param"
for param in options.param:
	check_exists(param)
	opt+="  "+param
if options.verbose:
	opt+=" --verbose"
if options.solute != None:
	opt+=" --solute "+options.solute

path_script_namd=os.path.dirname(os.path.abspath(__file__))+"/../NAMD/gen_structure"
check_exists(path_script_namd)

command=path_script_namd+" --psf "+options.topology+opt
if options.verbose:
	print "executing "+command+" ..."
os.system(command)
